#Imagen que voy a utilizar como base
FROM httpd:alpine

LABEL maintainer="Walter Gaitan"
LABEL project="bootcamp"

#Modificaciones sobre la imagen que he utilizado como base, en este caso alpine
COPY ./content /usr/local/apache2/htdocs/
