# Utilizar la imagen de nginx con la version requerida
FROM nginx:alpine

# Copiar el archivo index.html de la carpeta source desde el host a la carpeta del contenedor
COPY ./src/index.html /usr/share/nginx/html