version: "3.8"
services:
  web:
    image: nginx
    volumes:
      - ./bootcamp-web:/usr/share/nginx/html
    ports:
      - "9999:80"
    environment:
      - NGINX_PORT=80
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"